# Site settings
title: r3kind1e - Cybersecurity Insights and Penetration Testing
SEOTitle: r3kind1e | Penetration Testing Engineer | Cybersecurity Blog | 网络安全博客
header-img: img/home-bg.png
email: r3kind1e@yahoo.com
description: "Join r3kind1e, a rising Penetration Testing Engineer, as she shares her journey and insights into the world of cybersecurity. Dive into detailed blog posts covering topics from ethical hacking to web application security."
keyword: "r3kind1e, Cybersecurity, Penetration Testing, Ethical Hacking, Web Application Security, Log4Shell, Cybersecurity Blog, Security Vulnerabilities, Network Security."
url: "https://r3kind1e.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username:    r3kind1e
# twitter_username:   
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true                # 没有行号会显得代码块很矮。
      start_line: 1



# Disqus settings
disqus_username: r3kind1e

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-27814955-0'            # Format: UA-xxxxxx-xx
ga_domain: r3kind1e.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Initially studied English before switching to Computer Science. Completed most Computer Science credits within a year and a half. Took a year off for self-study in cybersecurity and interned as a Penetration Testing Engineer at Hillstone Networks."
sidebar-avatar: /img/touxiang.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false       # 离线缓存功能，默认值为true，因为存在文章加载不出来的问题，所以这里改为false，可以及时刷新文章。



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "whale3070",
        href: "https://whale3070.github.io/"
    # },{
#         title: "Sherry Woo",
#         href: "https://sherrywoo.me/"
#     },{
#         title: "Kun Qian",
#         href: "http://kunq.me"
#     },{
#         title: "Ebn Zhang",
#         href: "http://ebnbin.com/"
#     },{
#         title: "SmdCn",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "JiyinYiyong",
#         href: "http://tiye.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
#         title: "尹峰以为",
#         href: "http://ingf.github.io/"
    }
]
